---
kind: pipeline
name: default

platform:
  os: linux
  arch: amd64

steps:
- name: build and push to quay.io
  image: plugins/docker
  settings:
    password:
      from_secret: QUAY_PWORD
    registry: quay.io
    repo: quay.io/esdcdevx/redirect
    tags:
      - latest
    username: esdcdevx+redirect